apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  name: demobank-account-svc
  labels:
    run: demobank-account
spec:
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 3000
    protocol: TCP
    name: https
  selector:
    run: demobank-account
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demobank-account
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: demobank-account
    spec:
      containers:
      - name: demobank-account
        image: demobank.azurecr.io/osvaldofa/demobank.transaction:latest
        ports:
        - containerPort: 80